language: go

sudo: false

go:
  - 1.5
  - 1.6
  - tip

install:
  - go get
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install --update

script:
  - gometalinter ./... --deadline=30s
