language: go

sudo: false

go:
  - 1.5
  - 1.6
  - tip

install:
  - go get -v ./...
  - go get -u github.com/stretchr/testify/assert
  - go get -u github.com/alecthomas/gometalinter
  - gometalinter --install --update
  - go get -u golang.org/x/tools/cmd/cover
  - go get -u github.com/mattn/goveralls

script:
  - gometalinter ./... --deadline=1m
  - goveralls -v -service=travis-ci
